# deploy.yml
name: deploy to baota
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:17
      - name: use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'dist/*'
          target: '/www/wwwroot/jun.sh'
          strip_components: 1
