name: Deploy Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: npm install && npm run build
      - name: Deploy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'dist/*'
          target: '/www/wwwroot/jun.sh'
          strip_components: 1
          rm: 'true'
